services:
  php-fpm:
    image: euclid1990/php5.6-fpm
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
    networks:
      - app_network

  nginx:
    image: nginx:latest
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  node:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: tail -F anything

networks:
  app_network:

volumes:
  mysql_data:
